language: python

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build

install:
  - pip install -r https://raw.githubusercontent.com/ProgVal/Limnoria/master/requirements.txt --upgrade
  - pip install git+https://github.com/ProgVal/Limnoria.git@master --upgrade
  - pip install -r requirements.txt

script:
  - echo $TRAVIS_PYTHON_VERSION
  - cd ..
  - mv r3bot-irc RealRaum
  - supybot-test RealRaum # --no-network --disable-multiprocessing

notifications:
    email: false

matrix:
  fast_finish: true
